name: SecondAC
version: 1.0
main: me.secondanticheat.AntiCheat
author: Phon1x
description: Pokročilý AntiCheat plugin pro Minecraft servery
api-version: 1.16

commands:
  anticheat:
    description: Zobrazí stav anti-cheatu
    usage: /anticheat
    permission: secondac.admin
  ban:
    description: Manuální ban hráče
    usage: /ban <hráč> <důvod>
    permission: secondac.admin
  unban:
    description: Odbanování hráče pomocí ID
    usage: /unban <ban_id>
    permission: secondac.admin

permissions:
  secondac.admin:
    description: Oprávnění k administraci SecondAC
    default: op
